name: Web Automation Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Configure bundler
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle config set --local without 'development test'
        bundle lock --add-platform x86_64-linux

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Run tests
      run: bundle exec cucumber --format json --out reports/cucumber.json

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          reports/
          screenshot_*.png

    - name: Publish to Cucumber Reports
      if: always()
      id: publish-report
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.Cucumber_TOKEN }}
        path: reports/cucumber.json
        results: reports/cucumber.json

    - name: Send Report to Feishu
      if: success()
      run: |
        REPORT_URL="${{ steps.publish-report.outputs.report_url }}"
        TEST_STATUS="${{ job.status }}"
        
        # 构建飞书消息内容
        MESSAGE="{
          \"msg_type\": \"interactive\",
          \"card\": {
            \"config\": {
              \"wide_screen_mode\": true
            },
            \"header\": {
              \"title\": {
                \"tag\": \"plain_text\",
                \"content\": \"Web自动化测试报告\"
              },
              \"template\": \"${{ job.status == 'success' && 'green' || 'red' }}\"
            },
            \"elements\": [
              {
                \"tag\": \"div\",
                \"text\": {
                  \"tag\": \"lark_md\",
                  \"content\": \"**测试状态：**${{ job.status }}\\n**分支：**${{ github.ref_name }}\\n**提交者：**${{ github.actor }}\\n**提交信息：**${{ github.event.head_commit.message }}\"
                }
              },
              {
                \"tag\": \"action\",
                \"actions\": [
                  {
                    \"tag\": \"button\",
                    \"text\": {
                      \"tag\": \"plain_text\",
                      \"content\": \"查看详细报告\"
                    },
                    \"url\": \"${REPORT_URL}\",
                    \"type\": \"default\"
                  }
                ]
              }
            ]
          }
        }"
        
        # 发送消息到飞书
        curl -X POST -H "Content-Type: application/json" \
          -d "$MESSAGE" \
          ${{ secrets.FEISHU_WEBHOOK_URL }}